apiVersion: v2
name: grafana
description: Grafana dashboards and visualization
type: application
version: 1.0.0

dependencies:
  - name: grafana
    version: "8.3.2"
    repository: https://grafana.github.io/helm-charts
